/* this file automatically generated by the Makefile */
#define COMPILER "clang++ -std=c++17 -Wno-everything"
#define OPTIMIZE "-O3"
#define CFLAGS   "-D__USE_FIXED_PROTOTYPES__ -O3"
#define OBJDIR   "obj"
